# Generated by Django 4.1.6 on 2023-03-06 12:17

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_bookinstance_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='language',
            field=models.CharField(max_length=200, null=True, verbose_name=catalog.models.Language),
        ),
    ]
