# Generated by Django 4.1.6 on 2023-03-06 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_bookinstance_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='language',
            field=models.ForeignKey(max_length=200, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.language'),
        ),
    ]
