# Generated by Django 4.1.6 on 2023-03-06 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_bookinstance_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='lang',
            field=models.CharField(help_text='Enter a book genre (e.g. Science Fiction)', max_length=20),
        ),
    ]
